make hydra happy
Infinisil/all-hies pull request #35
Opened 2019-11-26 14:56 UTC by reactormonk

Using `fetchFromGitHub` makes secure building possible.

2019-11-28 18:40 UTC, Infinisil commented
What hydra is that? And what's the problem with the previous code?

2019-11-29 08:04 UTC, reactormonk commented
The IOHK hydra. It's fine with `fetchFromGithub` because there's a hash included, but not with `fetchTarball`, even if it has a hash associated :-(

In general, `fetchFromGithub` is more specific anyway, so probably better to use it.

2019-11-29 15:44 UTC, infinisil requested changes
I see, sounds good then

2019-11-29 15:44 UTC, Infinisil commented on default.nix
> +    in import (fetchFromGitHub {
Can do `pkgs.fetchFromGitHub` here directly, no need to add an argument to the file for that

2020-07-25 02:17 UTC, Infinisil commented
Closing, especially since with #64, there's no chance to get Hydra happy with all the IFD happening :)

2020-07-25 02:17 UTC, closed without merging